### ISSUE TITLE
Support for running alarm when application is closed

### ISSUE THREAD

**Issue by jimjja** [baekgol/react-native-alarm-manager#11]
Thank you for creating a RN module for scheduling alarms with Alarm manager! This was something that was missing and needed by many developers. I successfully setup the package on my application and managed to run it. 

I found out that when the application is closed the alarm will not run. If I open the application, only then the scheduled alarm will run. Is this something you are thinking to add support for?

**Comment by baekgol** [comment]
Hello @jimjja!
I am so happy and thankful that you know the purpose of creating Alarm Manager.

By the way, does the alarm not work when the application is closed?
Alarm manager is designed so that the set alarm works even after the application is closed or the device is rebooted.
As you can see in the example, the alarm works even when the application is closed.
[Alarm stopping after activation](https://github.com/baekgol/react-native-alarm-manager#alarm-stopping-after-activation)

But it may be a bug I haven't found.
Right now I don't know what the cause is.
Please try the procedure in README.md one more time.
Have a nice day!

**Comment by jimjja** [comment]
You are absolutely right. It worked seamlessly. I believe the issue was with my config. 
Following on this, is there any roadmap of further functionality which you are thinking to include for this package?
Maybe something the community can help with?

**Comment by baekgol** [comment]
Oh, is the problem solved? What is the cause? I wonder too.
Hmm.. I have no plans yet for further functionalities.
But I will update soon this package for IOS at the same functionalities.
I hope this gets more known.
Thank you for your opinion and thinking!
