### ISSUE TITLE
After alarm set if app kills from background getting error and unable to open the app

### ISSUE THREAD

**Issue by ravi2288** [baekgol/react-native-alarm-manager#8]
While developing i set the alarm and its working as expected, facing issue in case while app killed from background after setting alarm. Error is - **COULD NOT CONVERT CLASS android.os.UserHandle**
![68f1a191-6bcf-4927-8b4b-37406251bdcb](https://user-images.githubusercontent.com/8969951/161427949-89d87c9a-e75a-4997-a0bb-9d3713f1b0d3.jpeg)

after this error app not open until you reinstall it from android studio.
Below are steps i used for setup - 
1. npm i react-native-alarm-manager
2. Added receiver and service in manifest
3. adding broadcast receiver in MainActivity.java

any thing i missed in installation ?
Please suggest. Thanks

**Comment by baekgol** [comment]
Hello, @ravi2288.
I'm sorry to hear that you have a problem.
No, you did not miss the installation.
I see this error for the first time, so I don't know what is matter.
However, I searched this error and found this issue related with your problem.
https://github.com/wix/react-native-notifications/issues/287#issuecomment-595643518
It doesn't seem to work properly on Xiaomi models. But not sure.
Or, check your android sdk version. -> [Check android SDK](https://github.com/baekgol/react-native-alarm-manager#check-android-sdk)
I hope your problem is resolved quickly. Thanks.
